services:
  redis:
    container_name: redis-stack
    image: redis/redis-stack:7.4.0-v0
    hostname: redis
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis-data:/data
    profiles:
      - app
      - test

  celery:
    container_name: celery
    build: 
      context: .
      dockerfile: Docker/Celery/Dockerfile
    links:
      - redis
    depends_on:
      - redis
    profiles:
      - app
      - test

  web:
    container_name: backend
    build: 
      context: .
      dockerfile: Docker/Flask/Dockerfile
    ports:
      - "5000:5000"
    links:
      - redis
    depends_on:
      - redis
    profiles:
      - app

  test:
    container_name: test
    build: 
      context: .
      dockerfile: Docker/Test/Dockerfile
    command: ["pytest"]
    links:
      - redis
      - celery
    depends_on:
      - redis
      - celery
    profiles:
      - test

volumes:
  redis-data: