services:
  web:
    container_name: backend
    build: 
      context: .
      dockerfile: Dockerfiles/Flask/Dockerfile
    image: flask
    ports:
      - "5000:5000"
    links:
      - redis
    depends_on:
      - redis

  redis:
    container_name: redis-stack
    image: redis/redis-stack:latest
    hostname: redis
    ports:
      - "6379:6379"
      - "8001:8001"

  celery:
    container_name: celery
    build: 
      context: .
      dockerfile: Dockerfiles/Celery/Dockerfile
    links:
      - redis
    depends_on:
      - redis